version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "19:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - u3u
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.11.1
    - 4.14.2
    - 4.16.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.8
  - dependency-name: npm
    versions:
    - 6.14.10
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: vue-router
    versions:
    - 3.4.9
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  - dependency-name: all-contributors-cli
    versions:
    - 6.19.0
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
